name = "onda-backend"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "onda-db"
database_id = "b9e6ed38-323d-4445-a0e5-aeafd54c523a"

[[kv_namespaces]]
binding = "LOCATION_KV"
id = "808d3d09a4754653973f0e060cbc8edc"

[[r2_buckets]]
binding = "CERT_BUCKET"
bucket_name = "onda-certs"

[triggers]
crons = ["* * * * *"]

[vars]
FRONTEND_URL = "https://onda.genomic.cc"
